[general]
# dark theme
import = ["~/.config/alacritty/themes/themes/breeze.toml"]
# light theme
#import  = ["~/.config/alacritty/themes/themes/dayfox.toml"]

[scrolling]
history = 0

[font]
size = 17
[font.normal]
family = "FiraMono Nerd Font"

[window]
opacity = 0.9
