[general]
# dark theme
import = ["~/.config/alacritty/themes/themes/breeze.toml"]
# light theme
#import  = ["~/.config/alacritty/themes/themes/dayfox.toml"]

[scrolling]
history = 0

[font]
size = 8

[font.normal]
family = "FiraCode Nerd Font"

[window]
opacity = 1
